version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
            
    php:
        image: php:fpm
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./app:/app

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'QuocAnh-1809'
            POSTGRES_DB: 'firstapp'
        volumes:
            - postgresdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5440:5432

    # admin:
    #     image: adminer
    #     restart: always
    #     depends_on: 
    #         - postgres
    #     volumes:
    #         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #     ports:
    #         - 8081:8080

volumes:
    postgresdata: {}


#VERSION2
# version: '3'
# services:
#     web:
#         build:
#             context: .
#             dockerfile: Dockerfile
#         ports:
#             - "80:80"
#         volumes:
#             - ./nginx.conf:/etc/nginx/nginx.conf
#             - ./app:/app
            
#     php:
#         image: php:fpm
#         volumes:
#             - ./app:/app

#     postgres:
#         image: postgres:latest
#         environment:
#             POSTGRES_USER: 'postgres'
#             POSTGRES_PASSWORD: 'QuocAnh-1809'
#             POSTGRES_DB: 'firstapp'
#         volumes:
#             - postgresdata:/var/lib/postgresql/data
#             - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#         ports:
#             - 5440:5432
# volumes:
#     postgresdata: {}